### ISSUE TITLE
Баг ? 

### ISSUE THREAD

**Issue by Fedor858** [Fanamurov/larrock-core#72]
После composer require fanamurov/larrock-core   - 
> @php artisan package:discover
ReflectionException  : Class command.larrock:addAdmin does not exist
at C:\laravel\OSPanel\domains\larrock\vendor\laravel\framework\src\Illuminate\Container\Container.php: 767
763|         if ($concrete instanceof Closure) {
    764|             return $concrete($this, $this->getLastParameterOverride());
    765|         }
    766|
  > 767|         $reflector = new ReflectionClass($concrete);
    768|
    769|         // If the type is not instantiable, the developer is attempting to resolve
    770|         // an abstract type such as an Interface of Abstract Class and there is
    771|         // no binding registered for the abstractions so we need to bail out.

**Comment by Fanamurov** [comment]
Здравствуйте!
Да, баг, сейчас поправлю

**Comment by Fanamurov** [comment]
@Fedor858 большое спасибо за сигнал. 16 марта внес изменения в процесс установки, чем поломал сам процесс. В версии larrock-core 1.2.10 установка исправлена и проходит корректно

**Comment by Fanamurov** [comment]
@Fedor858 Баг поправлен в версии larrock-core 1.3.5
Будьте внимательны, немного изменился процесс установки.
Теперь перед larrock:install нужно выполнить larrock:installcorepackages
