### ISSUE TITLE
php artisan larrock:manager - ошибки

### ISSUE THREAD

**Issue by Fedor858** [Fanamurov/larrock-core#75]
В процессе установки -
После  выполнения   php artisan larrock:install -
[InvalidArgumentException]
Could not find package fanamurov/larrock-*имя пакета* in a version matching 1.0
Аналогично после   php artisan larrock:manager
Но если  ставить  пакеты  отдельно как  composer require fanamurov/larrock-*имя пакета* то все ставится корректно

Пакеты   поставил вручную,установка теперь завершена  корректно  но при  входе в  админку - 
lluminate \ Database \ QueryException (42000)
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'larrock.menu.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select * from `menu` where `active` = 1 group by `type`)

**Comment by Fanamurov** [comment]
Запустите php artisan larrock:check
Там вам будет написано о том, что у вас включен строгий режим в mysql
Нужно в конфиге /config/database.php установить в connections -> mysql ->
'strict' => false

==== 
А про 
"Could not find package fanamurov/larrock-имя пакета in a version matching 1.0"
весьма странно, почему так, пока не могу воспроизвести

**Comment by Fanamurov** [comment]
@Fedor858 
По поводу "Could not find package fanamurov/larrock-имя пакета in a version matching 1.0"
Удалите все файлы и заново начните установку через http://larrock-cms.ru/feed/tekhnicheskaya-dokumentatsiya/bazovye-znaniya/ustanovka-larrockcms

Видимо у вас в composer json выглядит не так:
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "fanamurov/larrock-admin-seo": "^1.0",
        "fanamurov/larrock-blocks": "^1.0",
        "fanamurov/larrock-cart": "^1.0",
        "fanamurov/larrock-catalog": "^1.0",
        "fanamurov/larrock-category": "^1.0",
        "fanamurov/larrock-contact": "^1.0",
        "fanamurov/larrock-core": "^1.2",
        "fanamurov/larrock-discount": "^1.0",
        "fanamurov/larrock-feed": "^1.0",
        "fanamurov/larrock-menu": "^1.0",
        "fanamurov/larrock-pages": "^1.0",
        "fanamurov/larrock-reviews": "^1.0",
        "fanamurov/larrock-search": "^1.0",
        "fanamurov/larrock-smartbanners": "^1.0",
        "fanamurov/larrock-users": "^1.0",
        "fanamurov/larrock-wizard": "^1.0",
        "fanamurov/larrock-yandex-kassa": "^1.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Ну или вариант два. Привести свой composer.json к виду приведенного выше и выполнить
composer update

**Comment by Fanamurov** [comment]
@Fedor858 и обязательно выполните сначала
```
composer self-update
```

у меня на всех машинах composer require fanamurov/имя пакета:^1.0 проходит успешно, может быть проблема в этом?
