### ISSUE TITLE
Проблема с установкой

### ISSUE THREAD

**Issue by yuri25** [Fanamurov/larrock-core#90]
Нормально дохожу до пункта php artisan larrock:install
Выбираю  - опубликовать ресурсы. Зависает на вот этом:
 [27] Tag: views
  [28] Tag: views-admin-core
  [29] Tag: views-front-core
 >
Дальше выхожу Ctrl^C.  И уже не  дает ни восстановить установку. Пишет такое:
The environment file is invalid: Dotenv values containing spaces must be surrounded by quotes.
Что такое может быть?
PHP 7.1.15  mysql 10.1.26-MariaDB

**Comment by Fanamurov** [comment]
Здравствуйте! В одной из версий была ошибка со значением в .env-файле. Откройте его у себя и вручную найдите одно константу где есть пробел и окружите ее кавычками
примерно так:
MAIL_TEMPLATE_PHONE=company phone
=> 
MAIL_TEMPLATE_PHONE='company phone'
и продолжите установку.

**Comment by Fanamurov** [comment]
Исправлено в версии 1.4.9

**Comment by yuri25** [comment]
У меня в .env  нет такой записи, вот все что есть касательно mail:
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

Выполняю также команду php artisan larrock:manager, выбираю 0 установить все....
Также зависает на вот этом:
  [27] Tag: views
  [28] Tag: views-admin-core
  [29] Tag: views-front-core
 >

Почему то кривая установка у меня.... отсутствует папка public.... Что я неправильно делаю? 
Ставлю по инструкции отсюда http://larrock-cms.ru/

**Comment by yuri25** [comment]
С десятой попытки установил.... теперь не дает авторизоваться админом:

```
BadMethodCallException
Method Illuminate\Database\Query\Builder::level does not exist.
```

`/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php`

`2616    throw new BadMethodCallException(sprintf(`

**Comment by yuri25** [comment]
Может из за MariaDB?  Да, у меня при миграции выдавало ошибку
`SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table users add unique users_email_unique(email))`

Ошибку устранил так, в config\database.php заменил 

`'charset' => 'utf8mb4',
 'collation' => 'utf8mb4_unicode_ci',`
на 
`'charset' => 'utf8',
'collation' => 'utf8_unicode_ci',`
Возможно нужно было как то по другому.... И подскажите база данных должна быть 
utf8_general_ci  или utf8mb4_general_ci  
Может из за этого у меня не получается?....

**Comment by yuri25** [comment]
Аналогично создал базу utf8mb4_general_ci. Ошибку устранил первым методом, что описан здесь http://laranotes.ru/notes/laravel-5-4-i-oshibka-specified-key-was-too-long
Правда еще одна ошибка появилась SQLSTATE[42000]: Syntax error or access violation: 1055.
Тоже пришлось в config/database.php   `strict => false`
Вроде все установилось... но публикация ресурсов зависает там же... и авторизация админом та же ошибка...
```
BadMethodCallException
Method Illuminate\Database\Query\Builder::level does not exist.
```
К сожалению нет возможности перейти с MariaDB на Mysql....

**Comment by Fanamurov** [comment]
По-умолчанию требуется Mysql 5.7. Такая ошибка свойственна для 5.6 и видимо, MariaDB.
Я сейчас попробую у себя (с MariaDB  не экспериментировал) и создам патч

**Comment by Fanamurov** [comment]
> BadMethodCallException
> Method Illuminate\Database\Query\Builder::level does not exist.

А вот насчет этого сейчас посмотрю

**Comment by Fanamurov** [comment]
В текущей версии ядра есть ошибка в larrock:manager, прошу прощения. Исправил в 1.4.10

Подготовил для вас архив с уже установленной полной версией LarrockCMS (внутри архива есть larrock.sql с дампом БД)
https://yadi.sk/d/fZY630RH3TwQWo

===
Для LarrockCMS требуется версия Mysql 5.7 (в предыдущей версии 5.6 нет полей типа json и другие настройки). Дамп из архива должен нормально у вас пройти (json-поля переделаны в text(это не решение, но все посмотреть хватит))

**Comment by yuri25** [comment]
А я в свою очередь обновлю MariaDB до актуальной версии.... У меня сейчас MariaDB 10.1 do not support JSON ( Нужно обновить до 10.2.14

**Comment by yuri25** [comment]
Обновил MariaDB до 10.2.14, установка прошла нормально. Ошибки, связанные с неподдержкой json исчезли, но эта осталась  SQLSTATE[42000]: Syntax error or access violation: 1055. Пришлось  в config/database.php strict => false.   
И по прежнему не публикует ресурсы и осталась ошибка при авторизации админом.... BadMethodCallException
Method Illuminate\Database\Query\Builder::level does not exist.

Видать не судьба для MariaDB:((

**Comment by Fanamurov** [comment]
`BadMethodCallException
Method Illuminate\Database\Query\Builder::level does not exist.`
это не связано с MariaDB... Это связано с тем, что установка прошла некорректно.
В админку вас непускает потому что 
config/auth.php должен выглядеть так: https://github.com/Fanamurov/larrock-core/blob/master/configVendor/auth.php
Обратите внимание настроку: https://github.com/Fanamurov/larrock-core/blob/master/configVendor/auth.php#L70

===
По итогу могу предположить что публикация ресурсов не прошла вообще. 
Все из этой папки: https://github.com/Fanamurov/larrock-core/tree/master/configVendor
должно оказаться в /config с заменой оригинальных файлов

**Comment by yuri25** [comment]
Попробую еще раз все поставить.

**Comment by Fanamurov** [comment]
@yuri25 Хорошо. Я этот тикет закрою, в случае проблем, пожалуйста, создайте новый
